-- this plugin is used to auto complete <tag></tag>
return {
    "windwp/nvim-ts-autotag",
    ft = {
        "html",
        "javascript",
        "typescript",
        "javascriptreact",
        "typescriptreact",
        "svelte",
        "vue",
        "tsx",
        "jsx",
        "rescript",
        "xml",
        "php",
        "markdown",
        "glimmer",
        "handlebars",
        "hbs",
    },
    config = function()
        require("nvim-ts-autotag").setup({
            skip_tags = {
                "area",
                "base",
                "br",
                "col",
                "command",
                "embed",
                "hr",
                "img",
                "slot",
                "input",
                "keygen",
                "link",
                "meta",
                "param",
                "source",
                "track",
                "wbr",
                "menuitem",
            },
        })
    end,
}
